name: products.conholdate.cloud

on:
  workflow_dispatch:
  # schedule:
  #  - cron: '55 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Ceph / S3 credentials & settings (PROD)
      AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_S3_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: "true"
      # IMPORTANT: Use the same endpoint your deploy script used
      AWS_ENDPOINT_URL: https://s3-admin.dynabic.com
      # (Optional) Bunny API key already in secrets.BUNNY_API_KEY

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: conholdate-cloud/products.conholdate.cloud
          token: ${{ secrets.REPO_TOKEN }}
          ref: main
          submodules: true 
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true 

      - name: Build site
        run: hugo --minify

      # Ensure AWS CLI v2 and configure Ceph-friendly S3 options
      - name: Ensure AWS CLI v2 and configure S3
        run: |
          set -e
          if ! aws --version | grep -q 'aws-cli/2'; then
            curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install --update
          fi
          aws --version
          # Ceph-friendly settings:
          aws configure set region "$AWS_DEFAULT_REGION"
          aws configure set s3.addressing_style path
          aws configure set s3.signature_version s3v4
          # Do NOT set checksum_mode to when_required (can break on some builds)
          # aws configure set s3.checksum_mode ENABLED

      - name: Sync to Ceph S3 (PROD)
        run: |
          aws s3 sync ./public/ s3://products-conholdate-cloud/ \
            --delete \
            --acl public-read
          # NOTE: AWS_ENDPOINT_URL makes the CLI hit Ceph automatically.
          # For first validation, we keep verbose output; add --only-show-errors later if you prefer.

      # Show helpful debug info IF sync fails
      - name: Debug AWS CLI if failed
        if: failure()
        run: |
          echo "Listing bucket (first 200 debug lines):"
          aws s3 ls s3://products-conholdate-cloud/ --debug | head -n 200

      - name: Purge BunnyCDN Cache
        if: success()
        run: |
          curl -siG \
            -H "X-Api-Key: ${{ secrets.BUNNY_API_KEY }}" \
            --data-urlencode "url=https://products.conholdate.cloud" \
            "https://api.dynabic.com/bn/purge?async=true"
